# blah: blah.o 
# 	cc blah.o -o blah  

# blah.o: blah.c 
# 	cc -c blah.c -o blah.o

# blah.c: 
# 	echo "int main() { return 0; } > blah.c" 

# clean:
# 	rm blah *.o



# some_file: other_file
# 	echo "This will always run, and runs second"
# 	touch some_file

# other_file: 
# 	echo "This will always run, and runs first"


# some_file:
# 	touch some_file

# clean: 
# 	rm -f some_file


# files:= file1 file2

# some_file: ${files}
# 	echo "Look at this variable: " ${files}

# file1: 
# 	touch file1
# file2: 
# 	touch file2

# clean: 
# 	rm -f file1 file2 some_file



# a := one two#a is set to the string "one two"
# b := 'one two' #Not recommended. b is set to the string "'one two'"

# all:
# 	printf '$a'
# 	printf $b



# Ссылаются на переменные, используя либо ${}, либо $()

# x := dude

# all:
# 	echo $(x)
# 	echo ${x}

# # Bad practice, but works
# 	echo $x



# all: one two three

# one: 
# 	touch one
# two:
# 	touch two
# three:
# 	touch three

# clean:
# 	rm -f one two three




hello:
	@echo "Hello"










